# Generated by Django 2.2.6 on 2019-10-17 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produto',
            new_name='Lanche',
        ),
    ]
