# Generated by Django 2.2.6 on 2019-10-17 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_bebida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=4)),
                ('lanche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.Lanche')),
            ],
        ),
    ]
