# Generated by Django 2.2.6 on 2019-10-17 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='bebida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sistema.Bebida'),
            preserve_default=False,
        ),
    ]
