# Generated by Django 2.2.6 on 2019-10-28 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_auto_20191028_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='numero_pedido',
            new_name='numero',
        ),
    ]
