# Generated by Django 2.2.6 on 2019-10-28 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0011_remove_pedido_bebida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='lanche',
        ),
    ]
