# Generated by Django 2.2.6 on 2019-10-28 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0012_remove_pedido_lanche'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='numero',
            new_name='number',
        ),
    ]
