# Generated by Django 2.2.6 on 2019-10-29 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0013_auto_20191028_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='number',
            new_name='numero',
        ),
        migrations.AddField(
            model_name='pedido',
            name='bebida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sistema.Bebida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='lanche',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sistema.Lanche'),
            preserve_default=False,
        ),
    ]
