# Generated by Django 2.2.6 on 2019-10-29 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0014_auto_20191029_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mesa', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='numero',
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero_mesa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sistema.Mesa'),
            preserve_default=False,
        ),
    ]
