# Generated by Django 2.2.6 on 2019-10-29 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0016_pedido_numero_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='numero_mesa',
            new_name='mesa',
        ),
    ]
