# Generated by Django 2.2.6 on 2019-10-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0017_auto_20191029_0352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='lanche',
        ),
        migrations.AddField(
            model_name='pedido',
            name='lanche',
            field=models.ManyToManyField(to='sistema.Lanche'),
        ),
    ]
