# Generated by Django 2.2.6 on 2019-10-30 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0018_auto_20191030_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='mesa',
        ),
        migrations.DeleteModel(
            name='Mesa',
        ),
    ]
