# Generated by Django 2.2.6 on 2019-10-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0019_auto_20191030_0132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='bebida',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='lanche',
        ),
        migrations.AddField(
            model_name='lanche',
            name='pedido',
            field=models.ManyToManyField(to='sistema.Pedido'),
        ),
        migrations.DeleteModel(
            name='Bebida',
        ),
    ]
