# Generated by Django 2.2.6 on 2019-10-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0020_auto_20191030_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lanche',
            name='pedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='lanche',
            field=models.ManyToManyField(to='sistema.Lanche'),
        ),
    ]
