# Generated by Django 2.2.6 on 2019-10-31 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0023_auto_20191030_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='adicional',
            field=models.ManyToManyField(blank=True, to='sistema.Adicional'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='bebida',
            field=models.ManyToManyField(blank=True, to='sistema.Bebida'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='lanche',
            field=models.ManyToManyField(blank=True, to='sistema.Lanche'),
        ),
    ]
