# Generated by Django 2.2.6 on 2019-11-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0025_auto_20191101_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='lanche',
            name='ingrediente',
            field=models.ManyToManyField(blank=True, to='sistema.Ingrediente'),
        ),
    ]
