# Generated by Django 2.2.6 on 2019-11-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0026_lanche_ingrediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
