# Generated by Django 2.2.6 on 2019-11-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0030_caixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='data_abertura',
            field=models.DateField(verbose_name='Data de Abertura'),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='data_fechamento',
            field=models.DateField(null=True, verbose_name='Data de Fechamento'),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='observacao',
            field=models.CharField(max_length=50, verbose_name='Observação'),
        ),
    ]
