# Generated by Django 2.2.6 on 2019-11-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0032_lancamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='status',
            field=models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'fechado')], default='ABERTO', max_length=10),
        ),
    ]
