# Generated by Django 2.2.6 on 2019-11-03 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0033_caixa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='caixa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sistema.Caixa'),
            preserve_default=False,
        ),
    ]
