# Generated by Django 2.2.6 on 2019-11-04 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0034_pedido_caixa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lancamento',
            name='caixa',
        ),
        migrations.AlterField(
            model_name='caixa',
            name='data_abertura',
            field=models.DateField(verbose_name=datetime.date),
        ),
    ]
