# Generated by Django 2.2.6 on 2019-11-04 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0035_auto_20191104_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sistema.Pedido'),
            preserve_default=False,
        ),
    ]
