# Generated by Django 2.2.6 on 2019-11-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0036_lancamento_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='operacao',
            field=models.CharField(choices=[('CREDITO', 'credito'), ('DEBITO', 'debito'), ('DINHEIRO', 'dinheiro')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
