# Generated by Django 2.2.6 on 2019-11-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0037_lancamento_operacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(max_length=5),
        ),
    ]
